[workspace]
resolver = "2"

members = [
    "contracts/did_registry",
    "contracts/credential",
    "contracts/zk_verifier",
    "contracts/nullifier",
    "contracts/issuer_registry",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
publish = false

[workspace.dependencies]
soroban-sdk = { version = "27.0.0" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
