[package]
name = "verity_did_registry"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version = "1.84.0"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
testutils = []

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
