[package]
name = "verity_credential"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version = "1.84.0"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
testutils = []

[dependencies]
soroban-sdk = { workspace = true }
verity_did_registry = { path = "../did_registry" }
verity_issuer_registry = { path = "../issuer_registry" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
verity_did_registry = { path = "../did_registry", features = ["testutils"] }
verity_issuer_registry = { path = "../issuer_registry", features = ["testutils"] }